server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    # 【关键修改2】将基础连接信息直接放在 spring.datasource 下，不要包在 druid 里
    driver-class-name: ${lz.datasource.driver-class-name}
    url: jdbc:mysql://${lz.datasource.host}:${lz.datasource.port}/${lz.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${lz.datasource.username}
    password: ${lz.datasource.password}
  servlet:
    multipart:
      #开启多段上传
      enabled: true
      #最大请求大小
      max-file-size: 10MB
      #最大文件大小
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lz.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.lz.medical.mapper: debug
    com.lz.medical.service: info
    com.lz.medical.controller: info

lz:
  jwt:
    user-secret-key: lznb
    user-ttl: 57600000
    user-token-name: authentication
    admin-secret-key: lzhh
    admin-ttl: 57600000
    admin-token-name: token
    doctor-secret-key: lzhhh
    doctor-ttl: 57600000
    doctor-token-name: authorization
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}